### ISSUE TITLE
Compatibility with ModelsBuilder gone

### ISSUE THREAD

**Issue by kipusoep** [kgiszewski/uWestFest#33] opened 2016-05-18 12:49 UTC
Everything was working fine with ModelsBuilder, but now something changed with multiple urls and the PropertyValueConverter broke.
ModelsBuilder generates the following:

```
[ImplementPropertyType("link")]
public UrlPicker.Umbraco.Models.UrlPicker Link
{
	get { return this.GetPropertyValue<UrlPicker.Umbraco.Models.UrlPicker>("link"); }
}
```

This should be:
```
this.GetPropertyValue<List<UrlPicker.Umbraco.Models.UrlPicker>>("link")
```
because of the change.

**Comment by kgiszewski** [comment] 2016-06-08 12:38
@kipusoep sorry for the late response. 

Perhaps @bjarnef can assist?

**Comment by kipusoep** [comment] 2016-07-19 07:48
Any updates? :-)

**Comment by luuksommers** [comment] 2016-07-19 07:50
Running into the same problem.

**Comment by kgiszewski** [comment] 2016-07-19 11:43
Unfortunately I won't be of much help since I have no experience with models builder. To compound it, I no longer work with Umbraco on a daily basis. I'm more than willing to accept a PR.

**Comment by Jeavon** [comment] 2016-07-19 12:12
@kgiszewski I've just sent you a PR #34 for a quick fix

I think the VC should really not return a list, I'll do some further work on it, do you feel you could give me repo write access?

**Comment by Jeavon** [comment] 2016-07-19 12:14
I will also make it adjust between returning a collection and a single object depending on the setting of the prevalue

**Comment by kipusoep** [comment] 2016-07-19 12:17
That would be awesome @Jeavon

**Comment by Jeavon** [comment] 2016-07-19 15:01
Ok, various improvements committed in PR #34 

I guess this is "un-breaking" :wink:

I also noticed a UI bug when testing, if I try to add links with external urls, Umbraco wouldn't save my changes, they just disappeared, using a internal node it was fine, perhaps @bjarnef could look at that?

**Comment by kgiszewski** [comment] 2016-07-19 15:04
Thx @jeavon

**Comment by kgiszewski** [comment] 2016-07-21 01:09
@Jeavon, I just now noticed your other comment about commit rights. Invitation sent ;)

**Comment by Jeavon** [comment] 2016-07-21 11:47
@kgiszewski cool, would you mind changing the default branch to develop, means PR's get targeted to it by default?

**Comment by kgiszewski** [comment] 2016-07-21 11:59
@Jeavon done.

**Comment by bjarnef** [comment] 2016-07-24 13:57
@Jeavon it actually works with with external urls, when selecting content or media node since callback of these execute `$scope.sync()` which update the model.value with the data in the pickers.

I noticed the issue for a short time, but when trying now I can't reproduce it..

**Comment by Jeavon** [comment] 2016-08-03 09:49
v0.16.0 resolves this issue

**Closed by Jeavon** 2016-08-03 09:49 UTC

**Comment by kipusoep** [comment] 2016-08-03 11:05
Thanks for the effort guys!
